name: Deploy package to NPM

on:
  release:
    types: [published]

jobs:
  deploy-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate npm package
        run: |
          npm run build
          npm version ${{ github.event.release.tag_name }}
        working-directory: app

      - name: Publish npm package
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --access public --ignore-scripts
        working-directory: app
        env:
          NPM_TOKEN: ${{ secrets.NPM_MIMIRORG_AUTH }}
